//To use the extension, install in vscode: humao.rest-client

### Registrar un nuevo usuario
POST http://localhost:8082/register
Content-Type: application/json

{
    "location_code": "sao pablo",
    "notification_schedule": 23200
}

### Registrar un nuevo usuario
POST http://localhost:8082/register
Content-Type: application/json

{
    "location_code": "florianopolis",
    "notification_schedule": 23260
}